### ISSUE TITLE
error send mensage

### ISSUE THREAD

**Issue by jsuceir** [orkestral/venom#1873] opened 2022-08-17 18:41 UTC
## Description
error send mensagem
[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [e.g. OSX 10.13.4, Windows 10]
- **Node version:** [e.g. Node 8, Node 14]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot
![image](https://user-images.githubusercontent.com/5115043/185217625-a0857e5a-1c48-4915-9299-9952865b297e.png)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jsuceir** [comment] 2022-08-17 18:43
v4.3.0

**Comment by acognigni-evotecnia** [comment] 2022-08-18 11:53
when submitting a bug, please fill the bug report for properly. you did the minimum work and pasted a screen capture of the bug instead of pasting the text itself. this combined with the lack of a descriptive title, a description ofr code samles means that even if the issue is fixed, no one can find your ticket if they have the same issue. 

Since you have not explained when the error occurs or shown a fragment of code, and my bot is sending messages without issues, this ticket should be closed as "cannot replicate"

**Closed** 2022-08-19 17:23 UTC
Labels: bug, needs triage
