### ISSUE TITLE
 message is missing critical data needed to download the file.

### ISSUE THREAD

**Issue by JoseDiaz2211** [orkestral/venom#613] opened 2021-02-19 16:19 UTC
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Venom version(s):** [2.2.4]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** [Windows 10]
- **Node version:** [v10.16.3]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
This problem happens when I am receiving my own messages in the onAnyMessager method

I need to see my own messages

Please when you can answer me
```

## Your Code
(node:10556) UnhandledPromiseRejectionWarning: Error: message is missing critical data needed to download the file.
    at Whatsapp.<anonymous> (C:\Users\Lugotech_RD_2\Desktop\PythonSele\Venuz\venom\dist\api\whatsapp.js:238:35)
    at step (C:\Users\Lugotech_RD_2\Desktop\PythonSele\Venuz\venom\dist\api\whatsapp.js:46:23)
    at Object.next (C:\Users\Lugotech_RD_2\Desktop\PythonSele\Venuz\venom\dist\api\whatsapp.js:27:53)
    at C:\Users\Lugotech_RD_2\Desktop\PythonSele\Venuz\venom\dist\api\whatsapp.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Lugotech_RD_2\Desktop\PythonSele\Venuz\venom\dist\api\whatsapp.js:17:12)
    at Whatsapp.decryptFile (C:\Users\Lugotech_RD_2\Desktop\PythonSele\Venuz\venom\dist\api\whatsapp.js:227:16)
    at client.onAnyMessage (C:\Users\Lugotech_RD_2\Desktop\PythonSele\Venuz\venom\examples\basic\index.js:347:37)
    at EventEmitter.<anonymous> (C:\Users\Lugotech_RD_2\Desktop\PythonSele\Venuz\venom\dist\api\layers\listener.layer.js:246:21)
    at EventEmitter.emit (events.js:198:13)
(node:10556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by NiedsonEmanoel** [comment] 2021-02-20 06:12
Duplicate of #572

**Comment by Lucipher** [comment] 2021-02-22 10:32
Duplicate of  https://github.com/orkestral/venom/issues/211

**Comment by orkestral** [comment] 2021-02-27 01:18
corrention in npm i venom-bot version 3.0.3

**Closed by orkestral** 2021-02-27 01:18 UTC
Labels: bug, needs triage
