### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property '__x_id' of undefined

### ISSUE THREAD

**Issue by gamadoleo** [orkestral/venom#690] opened 2021-03-03 11:24 UTC
## Description

Error: Evaluation failed: TypeError: Cannot read property '__x_id' of undefined
    at Object.window.WAPI.window.WAPI.getNewMessageId (D:\central_api\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:56799)
    at async Object.window.WAPI.window.WAPI.sendMessage (D:\central_api\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:37297)
    at ExecutionContext._evaluateInternal (D:\central_api\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (D:\central_api\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)

## Environment

- **Venom version(s):** v3.0.8
- **Browser:** Chrome 88
- **OS:** Windows
- **Node version:** v14.16.0

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

**Comment by antirek** [comment] 2021-03-04 10:31
describe more details
I have same problem on one venom instance, but I can't reproduce on my developer venom instance

**Comment by gamadoleo** [comment] 2021-03-04 11:12
> describe more details
> I have same problem on one venom instance, but I can't reproduce on my developer venom instance

I'm also not understanding, in fact on the same machine I have other instances of the api which works, but only this instance when running it connects correctly but when sending a message displays this error, I think it may be something specific to the device that is installed the WhatsApp.

**Comment by gamadoleo** [comment] 2021-03-04 11:26
> > describe more details
> > I have same problem on one venom instance, but I can't reproduce on my developer venom instance
> 
> I'm also not understanding, in fact on the same machine I have other instances of the api which works, but only this instance when running it connects correctly but when sending a message displays this error, I think it may be something specific to the device that is installed the WhatsApp.

Other details
Version web: 2.2106.5                                                                                                          
Theme: light

**Comment by antirek** [comment] 2021-03-04 16:03
Do you have any contacts in contact list of whatsapp account?

**Comment by gamadoleo** [comment] 2021-03-04 16:20
> Do you have any contacts in contact list of whatsapp account?

in fact whatsapp is from a third party, request some details to try to mitigate what is different in his case, and were you able to identify something different? don't have your contacts related?
The strangest thing is that I have other instances of the same machine that only works with this device that is generating this exception

**Comment by jonalan7** [comment] 2021-03-05 02:52
**What function are you using that is generating this error?**

**Comment by antirek** [comment] 2021-03-05 03:16
@jonalan7  sendText

**Comment by antirek** [comment] 2021-03-05 06:19
two whatsapp accounts with this problem:
one account problem is solved with upgrade whatsapp app from 2.20.206.44 to 2.21.4.22 (actual version).

But other on 2.21.4.22 and problem is actual ((((

**Comment by gamadoleo** [comment] 2021-03-05 13:03
> two whatsapp accounts with this problem:
> one account problem is solved with upgrade whatsapp app from 2.20.206.44 to 2.21.4.22 (actual version).
> 
> But other on 2.21.4.22 and problem is actual ((((

any news?
more details:
here I updated to the latest version available, but still has a problem
device: with android 10

**Comment by jonalan7** [comment] 2021-03-10 12:44
**I believe that the problem has been fixed, so I will close this issue, if the problem happens again just reopen again!**

**Closed** 2021-03-10 12:45 UTC
Labels: bug, needs triage
