### ISSUE TITLE
If my project has tokens, the browser not is opened

### ISSUE THREAD

**Issue by yuryalencar** [orkestral/venom#2377] opened 2023-07-09 00:57 UTC
## Description

Always if I already have the tokens saved. My browser does not open and throws a new error. I tried with two configurations, without `browserArgs` and with `browserArgs: ['--no-sandbox']`, but the error is similar.

**if I delete tokens works again**

## Environment

- **Venom version(s):** [5.0.11]
- **Browser:** [Chrome/114.0.5735.198]
- **OS:** [OSX 13.4.1]
- **Node version:** [v19.7.0 and v17.8.0]

## Steps to Reproduce

1. Connect a device to venom bot version 5.0.11
2. Stop the bot service
3. Start the bot service again using the same tokens as before

## Log Output

```
You're up to date 🎉🎉🎉

[initBrowser]

Path Google-Chrome:  /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Chrome Version: Chrome/114.0.5735.198
aqui
Error: Failed to launch the browser process! undefined


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/Users/yuryalencar/Documents/personal/teasy-bot/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259:24)
    at ChildProcess.emit (node:events:524:35)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
✖ Error no open browser....

[noOpenBrowser]

Error no open browser....
```

if I run with `browserArgs: ['--no-sandbox']`

```
You're up to date 🎉🎉🎉

[initBrowser]

Path Google-Chrome:  /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Chrome Version: Chrome/114.0.5735.198
aqui
Error: Failed to launch the browser process! undefined
[72789:259:0708/211239.932683:ERROR:process_singleton_posix.cc(334)] Failed to create /Users/yuryalencar/Documents/personal/teasy-bot/yuryalencar-tokens/yuryalencar/SingletonLock: File exists (17)
[72789:45315:0708/211239.957674:ERROR:trust_store_mac.cc(844)] Error parsing certificate:
ERROR: The policy qualifiers SEQUENCE is empty
ERROR: Failed parsing policy qualifiers
ERROR: Failed parsing certificate policies



TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/Users/yuryalencar/Documents/personal/teasy-bot/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259:24)
    at ChildProcess.emit (node:events:524:35)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
✖ Error no open browser....

[noOpenBrowser]

Error no open browser....
```
## My code

```
const botConfig = {
  folderNameToken: `${BOT_NAME}-tokens`,
  multidevice: true,
  disableWelcome: true,
  logQR: true,
};

const bot = await venom.create({
  session: `${BOT_NAME}`,
  catchQR,
  statusFind,
  ...botConfig,
});
```

**Comment by gac256** [comment] 2023-07-09 04:24
some problem

**Comment by jas7i** [comment] 2023-07-09 06:49
same problem here, I am a Mac user, and I have a WhatsApp server project, when I start the first time my server using NPM start. it's working fine, but after a second time  start it returns the same error and then it is not working anymore.
<img width="1280" alt="image" src="https://github.com/orkestral/venom/assets/78642021/78abb157-980a-417e-9685-8144d988ee27">
I tried many times by changes to my code but still not works.
Anyone can fix this?

**Comment by jas7i** [comment] 2023-07-09 15:41
> session: `${BOT_NAME}`,



> ## Description
> Always if I already have the tokens saved. My browser does not open and throws a new error. I tried with two configurations, without `browserArgs` and with `browserArgs: ['--no-sandbox']`, but the error is similar.
> 
> **if I delete tokens works again**
> 
> ## Environment
> * **Venom version(s):** [5.0.11]
> * **Browser:** [Chrome/114.0.5735.198]
> * **OS:** [OSX 13.4.1]
> * **Node version:** [v19.7.0 and v17.8.0]
> 
> ## Steps to Reproduce
> 1. Connect a device to venom bot version 5.0.11
> 2. Stop the bot service
> 3. Start the bot service again using the same tokens as before
> 
> ## Log Output
> ```
> You're up to date 🎉🎉🎉
> 
> [initBrowser]
> 
> Path Google-Chrome:  /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> Chrome Version: Chrome/114.0.5735.198
> aqui
> Error: Failed to launch the browser process! undefined
> 
> 
> TROUBLESHOOTING: https://pptr.dev/troubleshooting
> 
>     at ChildProcess.onClose (/Users/yuryalencar/Documents/personal/teasy-bot/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259:24)
>     at ChildProcess.emit (node:events:524:35)
>     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
> ✖ Error no open browser....
> 
> [noOpenBrowser]
> 
> Error no open browser....
> ```
> 
> if I run with `browserArgs: ['--no-sandbox']`
> 
> ```
> You're up to date 🎉🎉🎉
> 
> [initBrowser]
> 
> Path Google-Chrome:  /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> Chrome Version: Chrome/114.0.5735.198
> aqui
> Error: Failed to launch the browser process! undefined
> [72789:259:0708/211239.932683:ERROR:process_singleton_posix.cc(334)] Failed to create /Users/yuryalencar/Documents/personal/teasy-bot/yuryalencar-tokens/yuryalencar/SingletonLock: File exists (17)
> [72789:45315:0708/211239.957674:ERROR:trust_store_mac.cc(844)] Error parsing certificate:
> ERROR: The policy qualifiers SEQUENCE is empty
> ERROR: Failed parsing policy qualifiers
> ERROR: Failed parsing certificate policies
> 
> 
> 
> TROUBLESHOOTING: https://pptr.dev/troubleshooting
> 
>     at ChildProcess.onClose (/Users/yuryalencar/Documents/personal/teasy-bot/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259:24)
>     at ChildProcess.emit (node:events:524:35)
>     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
> ✖ Error no open browser....
> 
> [noOpenBrowser]
> 
> Error no open browser....
> ```
> 
> ## My code
> ```
> const botConfig = {
>   folderNameToken: `${BOT_NAME}-tokens`,
>   multidevice: true,
>   disableWelcome: true,
>   logQR: true,
> };
> 
> const bot = await venom.create({
>   session: `${BOT_NAME}`,
>   catchQR,
>   statusFind,
>   ...botConfig,
> });
> ```

I Have fixed this issue you can also do that on your end too.
Please make the session name dynamic from this  `  session: ${BOT_NAME}`  to  this`session = `'${Date.now()}'`;`.
Hope this will resolve your issue.
Thanks

**Comment by yuryalencar** [comment] 2023-07-09 15:41
@jas7i If you delete your tokens will work again. But I need to work with my tokens as before, without having to connect again

**Comment by yuryalencar** [comment] 2023-07-09 15:47
@jas7i with your solution I need to connect every time I start my project. But in the production stage, it can be a problem

**Comment by jas7i** [comment] 2023-07-09 15:50
Okay, but my issue only solved with dynamic session name

**Comment by titiloxx** [comment] 2023-07-09 20:14
Same problem here

**Comment by karein** [comment] 2023-07-10 11:33
Similar bugs: 
https://github.com/orkestral/venom/issues/2372
https://github.com/orkestral/venom/issues/2376

**Comment by yuryalencar** [comment] 2023-07-10 18:36
I tried updating as explained in similar issues using `headless: true` but it didn't work for me. If anyone got it, share it here with us 💪🏻

**Comment by yuryalencar** [comment] 2023-07-10 18:39
I saw that browsers changed headless mode, it probably may have affected the library (https://developer.chrome.com/articles/new-headless/)

**Comment by fedejuret** [comment] 2023-07-10 20:44
Same problem here...

**Comment by dmchandru** [comment] 2023-07-11 10:32
@yuryalencar, But it's working as expected in Windows Machine!

**Comment by rafaelsnnoleto** [comment] 2023-07-13 01:48
UP

**Comment by Skiepp** [comment] 2023-07-13 08:26
In my case, the issue is about the Singleton files. (expecially SingletonLock).
Removing the file itself allow the browser to start, but requires a fresh new login (not suitable for PROD)

**Comment by pv-vishnu-gps** [comment] 2023-07-14 12:37
i think issue caused by puppeteer .

https://github.com/puppeteer/puppeteer/issues/10517

**Comment by dmchandru** [comment] 2023-07-16 08:38
I have raise a PR to fix this bug https://github.com/orkestral/venom/pull/2394

**Comment by MoonDusk1996** [comment] 2023-07-18 17:35
Same here =/

**Comment by BLRocha** [comment] 2023-07-18 23:17
issue resolved by removing SimgletonLock symlink

path: node_modules/venom-bot/dist/controllers/browser.js

![image](https://github.com/orkestral/venom/assets/34800137/9d29f813-68f2-43ca-9ce7-b646e5c37bea)

**Comment by karein** [comment] 2023-07-28 18:40
> I tried updating as explained in similar issues using `headless: true` but it didn't work for me. If anyone got it, share it here with us 💪🏻

The new version 5.0.13 seems to work with an existing tokens folder and using `headless: true`
i tried creating a simple index.js and that's how it worked :

```javascript
    venom
    .create({
      session: 'sessionName',
      headless: true,
    }).then((client) => start(client))
    .catch((error) => {
      console.error('Erro ao criar o cliente do bot:', error);
    });
```
I had to wait a little bit of time after read the QR code/connect and then i was able to stop the server and restart. If i don't wait enough it asks for the QR again.

Also, before run i had to install `npm-check-updates` because this version return an error
https://github.com/orkestral/venom/issues/2417

hope this can help

**Comment by yuryalencar** [comment] 2023-07-28 21:11
I installed npm-check-updates, and when I connect works like before. But when I restart to use the last tokens doesn't work yet.

<img width="1130" alt="Screenshot 2023-07-28 at 18 09 04" src="https://github.com/orkestral/venom/assets/19940344/67319f3e-c783-4911-968c-21274b84bbe1">

**Comment by karein** [comment] 2023-07-31 12:47
I had the same `browser process!` error, but it looks like yours had some additional errors. So unfortunately it looks like our solutions will be different.

maybe these issues can help!?
https://github.com/orkestral/venom/pull/2399, https://github.com/orkestral/venom/issues/2408

hope you can solve yours issue too 👍

**Comment by BLRocha** [comment] 2023-07-31 19:15
try alter return of promise when reject(false) remove reject response or return accept(true).


https://github.com/orkestral/venom/commit/25b3fa8e6b40e7841e8381f2ec65f4aaa45a7688#diff-d8d150aa5b148952ce43234bbe8db37125e2e8c6d9515768def5d59766141b29R613-R62

**Closed** 2023-08-17 13:04 UTC
Labels: bug, needs triage
